openapi: 3.0.0
info:
  description: The service expose a RESTful API to send a candidate and its CV
  version: 1.0.0
  title: Referal
  contact:
    email: akulovdc@gmail.com
servers:
  - url: http://localhost:8080/
paths:
  /auth/login:
    post:
      summary: User login
      tags:
        - auth
      requestBody:
        description: User logging in
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
                  format: hash
            example:
              name: nickname
              password: F72f%AsUO2^kGAsgk1^ma
      responses:
        200:
          description: User successfuly logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    format: hash
              example:
                token: there_should_be_token
        401:
          description: Authentication is required
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 401
                message: Authentication is required
        500:
          description: Unexpected server state detected
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 500
                message: Unexpected server state detected
  /auth/signup:
    post:
      summary: User registration
      tags:
        - auth
      requestBody:
        description: User creating
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                password:
                  type: string
                  format: hash
            example:
              id: 256
              name: nickname
              password: F72f%AsUO2^kGAsgk1^ma
      responses:
        201:
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  password:
                    type: string
                    format: hash
              example:
                id: 256
                name: nickname
                password: F72f%AsUO2^kGAsgk1^ma
        400:
          description: The server cannot or will not process the request due to an apparent client error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 400
                message: The server cannot or will not process the request due to an apparent client error
        409:
          description: Request could not be processed because of conflict in the current state of the resource
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 409
                message: Request could not be processed because of conflict in the current state of the resource
        500:
          description: Unexpected server state detected
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 500
                message: Unexpected server state detected
        
  /cv/send:
    post:
      summary: Send CV of a particular candidate
      tags:
        - cv
      security:
        - referalAuth: []
      requestBody:
        description: Sending resume by user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fileId:
                  type: integer
                candidateName:
                  type: string
                candidateSurname:
                  type: string
            example:
              fileId: 1
              candidateName: Name
              candidateSurname: Surname
      responses:
        201:
          description: Candidate loaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  password:
                    type: string
                    format: hash
              example:
                id: 256
                name: nickname
                password: F72f%AsUO2^kGAsgk1^ma
        400:
          description: The server cannot or will not process the request due to an apparent client error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 400
                message: The server cannot or will not process the request due to an apparent client error
        401:
          description: Authentication is required
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 401
                message: Authentication is required
        500:
          description: Unexpected server state detected
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 500
                message: Unexpected server state detected
  /cv/requests:
    get:
      summary: Return a list with user requests
      tags:
        - cv
      security:
        - referalAuth: []
      responses:
        200:
          description: Getting user's requests history
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: integer
                    userid:
                      type: integer
                    candidateid: 
                      type: integer
                    status:
                      type: string
                      enum: [Rejected, Accepted, Submitted]
                    created:
                      type: string
                      format: timestamp
                    updated:
                      type: string
                      format: timestamp
              example:
                id: 1
                userid: 2
                candidateid: 3
                status: Rejected
                created: 2020-10-19 T 6:54:56 Z
                updated: 2020-10-19 T 6:54:56 Z
        401:
          description: Authentication is required
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 401
                message: Authentication is required
        500:
          description: Unexpected server state detected
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 500
                message: Unexpected server state detected
  /cv/load/{id}:
    get:
      summary: Load CV of a particular candidate
      tags:
        - cv
      security:
        - referalAuth: []
      parameters:
        - name: id
          in: path
          description: Should be entered candidate ID
          required: true
          schema:
            type: integer
          example:
            id: 1
      responses:
        200:
          description: CV successfuly loaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  link:
                    type: string
              example:
                link: example.com/path/to/file.txt
        400:
          description: The server cannot or will not process the request due to an apparent client error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 400
                message: The server cannot or will not process the request due to an apparent client error
        401:
          description: Authentication is required
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 401
                message: Authentication is required
        404:
          description: The requested resource could not be found but may be available in the future
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 404
                message: The requested resource could not be found but may be available in the future
        500:
          description: Unexpected server state detected
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 500
                message: Unexpected server state detected
  /cv/filter/{type}:
    get:
      summary: Filter CVs
      tags:
        - cv
      security:
        - referalAuth: []
      parameters:
        - name: type
          in: path
          description: Should be entered filtered type
          required: true
          schema:
            type: string
          example:
            type: name
      responses:
        200:
          description: Getting filtered candidates
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: integer
                    name:
                      type: string
                    surname:
                      type: string
                    cvosfileid:
                      type: integer
              example:
                id: 1
                name: name
                surname: surname
                cvosfileid: 256
        400:
          description: The server cannot or will not process the request due to an apparent client error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 400
                message: The server cannot or will not process the request due to an apparent client error
        401:
          description: Authentication is required
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 401
                message: Authentication is required
        404:
          description: The requested resource could not be found but may be available in the future
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 404
                message: The requested resource could not be found but may be available in the future
        500:
          description: Unexpected server state detected
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
              example:
                statusCode: 500
                message: Unexpected server state detected
        
components:
  securitySchemes:
    referalAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        password:
          type: string
          format: hash
        isadmin:
          type: boolean
          default: false
        created:
          type: string
          format: timestamp
        updated:
          type: string
          format: timestamp
      example:
        id: 1
        name: name
        password: password
        isadmin: false
        created: "2020-10-19 T 9:01 Z"
        updated: "2020-10-19 T 9:01 Z"
    Candidate:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        surname:
          type: string
        cvosfileid:
          type: integer
      example:
        id: 1
        name: name
        surname: surname
        cvosfileid: 1
    Request:
      type: object
      properties:
        id:
          type: integer
        userid:
          type: integer
        candidateid:
          type: integer
        status:
          type: string
          enum: [Rejected, Submitted, Accepted]
        created:
          type: string
          format: timestamp
        updated:
          type: string
          format: timestamp
